services:
  app:
    build: .
    container_name: totesbook_app
    ports:
      - "8080:8080"
      - "4848:4848"
    depends_on:
      - db
    environment:
      - JAVA_OPTS=-Xmx512m
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=totesbook
      - DB_USER=totesuser
      - DB_PASS=totespass
    volumes:
      # WAR en autodeploy
      - ./target/TotEsBook-1.0-SNAPSHOT.war:/opt/glassfish7/glassfish/domains/domain1/autodeploy/TotEsBook.war

  db:
    image: mysql:8.0
    container_name: totesbook_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: totesbook
      MYSQL_USER: totesuser
      MYSQL_PASSWORD: totespass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8081:8080"

volumes:
  mysql_data:
